spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://mel.db.elephantsql.com:5432/vxddpjox
    username: vxddpjox
    password: 6Z0hlQkOdPHbJRp-6hZWPFdUZu0MBofC
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
