server:
  port: 30030
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://mel.db.elephantsql.com:5432/vxddpjox
    username: vxddpjox
    password: 6Z0hlQkOdPHbJRp-6hZWPFdUZu0MBofC
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyJpaCompliantImpl
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect
        auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
logging:
  level:
    org:
      hibernate:
        SQL: debug
      type:
        descriptor:
          sql: trace
